keys:
  - &user_age age1rfksm77mney9g30lce8asxnrvergxuw5gnxrd9amkayjyzpsz4xqnxkf4u

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_age
